### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by saranshvora** [StanfordASL/DynSTGModeling#1]
Hi, thank you for making the code public. 

I am getting an error related to tensor type when I run test_online.py

`  File "C:\Users\vora\Desktop\TressPass\Code\DynSTGModeling\code\model\online_node_model.py", line 141, in obtain_encoded_tensor_dict
    TD["joint_present_orig"] = torch.cat([TD[robot_present + "_orig"], our_prediction_present], dim=1) # [bs/nbs, state_dim+pred_dim]
RuntimeError: Expected a Tensor of type torch.FloatTensor but found a type torch.cuda.FloatTensor for sequence element 1 in sequence argument at position #1 'tensors'
`

PS- can I also know the data format needed to be given to the network?

**Comment by BorisIvanovic** [comment]
Hi, thanks for your interest in this codebase. The solution here, since you're using a CPU, is to convert the parameters to CPU since they're currently saved after being trained on a GPU.

I think you've already found this solution, so I'll close this issue.

**Comment by BorisIvanovic** [comment]
I forgot to mention, but you can look at the data format by printing the shapes and contents of the tensors passed into the `incremental_forward` call here: https://github.com/StanfordASL/DynSTGModeling/blob/master/code/test_online.py#L228
