### ISSUE TITLE
Pedestrian/0 is not in this graph

### ISSUE THREAD

**Issue by saranshvora** [StanfordASL/DynSTGModeling#2]
Hi, I solved the previous error by changing it to CPU but I still want to use the GPU for the same. 
After I change it to the CPU then I get the following output:

`Loading from ../ewap-dataset/logs/models_28_Jan_2019_15_35_20\model_registrar-1999.pt
Loaded!

At t=0, have 24 nodes, 17 edges which uses 112.96 MBs of RAM.
t=1: took 0.39 s (= 2.58 Hz) and 24 nodes, 16 edges uses 116.66 MBs of RAM.
t=2: took 0.34 s (= 2.95 Hz) and 24 nodes, 16 edges uses 116.83 MBs of RAM.
t=3: took 0.31 s (= 3.21 Hz) and 24 nodes, 16 edges uses 116.97 MBs of RAM.
t=4: took 0.32 s (= 3.12 Hz) and 25 nodes, 16 edges uses 117.14 MBs of RAM.
t=5: took 0.43 s (= 2.30 Hz) and 22 nodes, 12 edges uses 130.80 MBs of RAM.
t=6: took 0.26 s (= 3.84 Hz) and 22 nodes, 11 edges uses 137.32 MBs of RAM.
t=7: took 0.52 s (= 1.92 Hz) and 22 nodes, 11 edges uses 146.02 MBs of RAM.
t=8: took 0.24 s (= 4.10 Hz) and 22 nodes, 10 edges uses 142.48 MBs of RAM.
t=9: took 0.25 s (= 3.98 Hz) and 22 nodes, 10 edges uses 148.12 MBs of RAM.
t=10: took 0.25 s (= 3.97 Hz) and 22 nodes, 10 edges uses 142.60 MBs of RAM.
t=11: took 0.23 s (= 4.35 Hz) and 22 nodes, 11 edges uses 148.10 MBs of RAM.
t=12: took 0.23 s (= 4.27 Hz) and 22 nodes, 11 edges uses 142.95 MBs of RAM.
t=13: took 0.23 s (= 4.29 Hz) and 22 nodes, 12 edges uses 144.37 MBs of RAM.
t=14: took 0.23 s (= 4.33 Hz) and 22 nodes, 13 edges uses 148.92 MBs of RAM.
t=15: took 0.22 s (= 4.57 Hz) and 22 nodes, 14 edges uses 146.37 MBs of RAM.
t=16: took 0.25 s (= 4.08 Hz) and 23 nodes, 17 edges uses 150.79 MBs of RAM.
t=17: took 0.25 s (= 4.03 Hz) and 23 nodes, 16 edges uses 144.25 MBs of RAM.
t=18: took 0.24 s (= 4.08 Hz) and 23 nodes, 16 edges uses 144.77 MBs of RAM.
t=19: took 0.26 s (= 3.85 Hz) and 23 nodes, 18 edges uses 147.86 MBs of RAM.
t=20: took 0.23 s (= 4.26 Hz) and 23 nodes, 20 edges uses 144.71 MBs of RAM.
t=21: took 0.25 s (= 4.02 Hz) and 23 nodes, 20 edges uses 149.22 MBs of RAM.
t=22: took 0.25 s (= 4.08 Hz) and 23 nodes, 21 edges uses 144.71 MBs of RAM.
t=23: took 0.24 s (= 4.15 Hz) and 23 nodes, 20 edges uses 145.87 MBs of RAM.
t=24: took 0.25 s (= 4.03 Hz) and 23 nodes, 20 edges uses 149.62 MBs of RAM.
t=25: took 0.24 s (= 4.22 Hz) and 23 nodes, 21 edges uses 145.03 MBs of RAM.
t=26: took 0.26 s (= 3.79 Hz) and 23 nodes, 21 edges uses 144.78 MBs of RAM.
t=27: took 0.24 s (= 4.17 Hz) and 23 nodes, 18 edges uses 147.97 MBs of RAM.
t=28: took 0.26 s (= 3.88 Hz) and 23 nodes, 19 edges uses 144.60 MBs of RAM.
t=29: took 0.24 s (= 4.17 Hz) and 23 nodes, 19 edges uses 148.77 MBs of RAM.
t=30: took 0.24 s (= 4.24 Hz) and 23 nodes, 18 edges uses 145.20 MBs of RAM.
t=31: took 0.25 s (= 4.03 Hz) and 23 nodes, 18 edges uses 146.63 MBs of RAM.
t=32: took 0.23 s (= 4.41 Hz) and 23 nodes, 18 edges uses 149.96 MBs of RAM.
t=33: took 0.24 s (= 4.12 Hz) and 23 nodes, 18 edges uses 145.87 MBs of RAM.
t=34: took 0.23 s (= 4.41 Hz) and 23 nodes, 18 edges uses 145.72 MBs of RAM.
t=35: took 0.24 s (= 4.10 Hz) and 23 nodes, 17 edges uses 148.70 MBs of RAM.
t=36: took 0.25 s (= 4.00 Hz) and 23 nodes, 16 edges uses 145.04 MBs of RAM.
t=37: took 0.24 s (= 4.11 Hz) and 23 nodes, 16 edges uses 145.39 MBs of RAM.
t=38: took 0.40 s (= 2.49 Hz) and 23 nodes, 16 edges uses 148.45 MBs of RAM.
t=39: took 0.23 s (= 4.42 Hz) and 23 nodes, 15 edges uses 145.41 MBs of RAM.
t=40: took 0.26 s (= 3.83 Hz) and 24 nodes, 17 edges uses 148.25 MBs of RAM.
t=41: took 0.24 s (= 4.22 Hz) and 23 nodes, 16 edges uses 146.03 MBs of RAM.
t=42: took 0.25 s (= 4.03 Hz) and 23 nodes, 17 edges uses 147.18 MBs of RAM.
t=43: took 0.24 s (= 4.12 Hz) and 23 nodes, 17 edges uses 150.51 MBs of RAM.
t=44: took 0.25 s (= 4.07 Hz) and 23 nodes, 16 edges uses 146.31 MBs of RAM.
t=45: took 0.24 s (= 4.13 Hz) and 23 nodes, 16 edges uses 148.22 MBs of RAM.
t=46: took 0.24 s (= 4.18 Hz) and 23 nodes, 15 edges uses 150.94 MBs of RAM.
t=47: took 0.24 s (= 4.22 Hz) and 23 nodes, 16 edges uses 146.42 MBs of RAM.
t=48: took 0.25 s (= 4.07 Hz) and 23 nodes, 18 edges uses 151.20 MBs of RAM.
t=49: took 0.23 s (= 4.27 Hz) and 23 nodes, 18 edges uses 146.47 MBs of RAM.
t=50: took 0.24 s (= 4.20 Hz) and 23 nodes, 19 edges uses 147.48 MBs of RAM.
t=51: took 0.24 s (= 4.18 Hz) and 23 nodes, 21 edges uses 150.88 MBs of RAM.
t=52: took 0.24 s (= 4.24 Hz) and 23 nodes, 22 edges uses 146.18 MBs of RAM.
t=53: took 0.23 s (= 4.33 Hz) and 23 nodes, 21 edges uses 146.69 MBs of RAM.
t=54: took 0.24 s (= 4.18 Hz) and 23 nodes, 20 edges uses 149.60 MBs of RAM.
t=55: took 0.25 s (= 4.05 Hz) and 23 nodes, 20 edges uses 146.55 MBs of RAM.
t=56: took 0.23 s (= 4.39 Hz) and 23 nodes, 21 edges uses 151.00 MBs of RAM.
t=57: took 0.23 s (= 4.26 Hz) and 23 nodes, 20 edges uses 146.32 MBs of RAM.
here
t=58: took 0.26 s (= 3.82 Hz) and 25 nodes, 23 edges uses 145.86 MBs of RAM.
Traceback (most recent call last):

  File "C:\DynSTGModeling\code\model\online_dyn_stg.py", line 54, in _remove_node_model
    raise ValueError('%s is not in this graph!' % str(node))
ValueError: Pedestrian/0 is not in this graph!

Process finished with exit code 1`

How can I deal with this? I tried with the NBA dataset as well but I get different errors there.

**Comment by BorisIvanovic** [comment]
Hi saranshvora,

Yes, I think I remember seeing this error myself as well, and I remember implementing some fix for it. Unfortunately, I forgot what the fix was as it's been a while and I've developed a lot more on top of this model. 

While this isn't a very satisfying answer, if you're willing to wait approximately one week I will upload a vastly improved version of this codebase which doesn't suffer from the same issue and works with more datasets (I'll also be available to help debug after then). In the meantime, I'll leave this issue open in case you find a fix yourself and want to update this.

**Comment by saranshvora** [comment]
Hi BorisIvanovic, 

Ah that's great thank you for the reply. Sure, no problem I will wait for the updated version. It is nice that you will also help me debug.
I changed the Robotnode to pedestrian/1 and it worked but I am not sure if it is the right way. 

Thank you very much.

**Comment by saranshvora** [comment]
hi @BorisIvanovic any updates on the updated version of the code?

**Comment by BorisIvanovic** [comment]
Hi @saranshvora, I'm so sorry about the delay :( I have a set of exams coming up which are preventing me from getting around to updating this codebase now. I absolutely plan to update this, but it might be another few weeks at the least. I'm very very sorry about this!!

In the meantime, I've uploaded a paper which will describe the new updates that I was planning to put here (the large codebase update I described was for this paper): https://arxiv.org/abs/1810.05993

**Comment by saranshvora** [comment]
Hi @BorisIvanovic no problem I understand. Thank you for the link and informing about the code. Good luck with your exams :)

**Comment by BorisIvanovic** [comment]
Hi @saranshvora, I have updated the codebase. 

Closing this issue, please open new ones if there are any new issues with the new code. Thanks!
