### ISSUE TITLE
Script to preprocess ETH dataset

### ISSUE THREAD

**Issue by karanpatel95** [StanfordASL/DynSTGModeling#3]
Hi,

Can you make a code public that you used to convert ETH dataset into given preprocessed data? Also, can you explain what do the last four columns in ```data_dict['input_dict'][node]``` represent?

**Comment by karanpatel95** [comment]
It looks like last four columns are for velocity and acceleration.

**Comment by BorisIvanovic** [comment]
Hi! 

Yes exactly, the indices are: 0 = x, 1 = y, 2 = vx, 3 = vy, 4 = ax, 5 = ay.

As for the scripts to preprocess them: I will be making a large-scale update to this codebase in the future which will have an updated model and additional datasets (with associated preprocessing scripts). Unfortunately, this will probably occur about a month from now, so please check back around then.
